# Generated by Django 5.0 on 2024-11-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datum_rođenja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
