# Generated by Django 5.0 on 2024-11-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_post_godiste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='pozicija',
        ),
        migrations.AddField(
            model_name='post',
            name='pozicije',
            field=models.ManyToManyField(blank=True, to='myapp.position'),
        ),
    ]
