# Generated by Django 5.0 on 2024-11-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_position_remove_post_pozicija_post_pozicije'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pozicije',
        ),
        migrations.AddField(
            model_name='post',
            name='pozicija',
            field=models.CharField(blank=True, choices=[('Golman', 'Golman'), ('Zadnji vezni', 'Zadnji vezni'), ('Prednji vezni', 'Prednji vezni'), ('Špic', 'Špic'), ('Levo krilo', 'Levo krilo'), ('Desno krilo', 'Desno krilo'), ('Levi bek', 'Levi bek'), ('Desni bek', 'Desni bek'), ('Štoper', 'Štoper')], default='Vezni igrač', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
