# Generated by Django 5.0 on 2024-11-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_post_pozicije_post_pozicija_delete_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Golman', 'Golman'), ('Zadnji vezni', 'Zadnji vezni'), ('Prednji vezni', 'Prednji vezni'), ('Špic', 'Špic'), ('Levo krilo', 'Levo krilo'), ('Desno krilo', 'Desno krilo'), ('Levi bek', 'Levi bek'), ('Desni bek', 'Desni bek'), ('Štoper', 'Štoper')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='pozicija',
        ),
        migrations.AddField(
            model_name='post',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='posts', to='myapp.position'),
        ),
    ]
